/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kalantar.samples.rxjava;

import io.reactivex.rxjava3.core.Observable;

public class App {
  public static void main(String[] args) {
    final Observable<Object> src = Observable.create(emitter -> {
      emitter.onNext("Alpha");
      emitter.onNext("Beta");
      emitter.onNext("Gamma");
      emitter.onComplete();
    });

    src.subscribe(o -> System.out.println("Received: " + o));
  }
}
