/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kalantar.samples.rxjava;

import io.reactivex.rxjava3.core.Observable;

public class App {
    public static void main(String[] args) {
        final Observable<String> emits = Observable.just("Alpha", "Beta", "Gamma");
        emits
            .map(String::length)
            .subscribe(System.out::println);
    }
}
