/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kalantar.samples.rxjava;

import io.reactivex.rxjava3.core.Observable;

import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) throws InterruptedException {
        final Observable<Long> interval =
            Observable.interval(1, TimeUnit.SECONDS);
        interval.subscribe(System.out::println);
        
        Thread.currentThread().join(5000);
    }
}
