/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kalantar.samples.rxjava;

import org.davidmoten.rx.jdbc.Database;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ReactiveAppTest {
    @Test
    void shouldLoadPersons() {
        Database db = Database.test();
        db.select("select name from person")
                .getAs(String.class)
                .blockingForEach(System.out::println);
    }
}
                                                                                                     